### ISSUE TITLE
Emit a event "up" before return the ElectronApp instance

### ISSUE THREAD

**Issue by mapaiva** [IonicaBizau/electronify#1]
Using eletronify I think I found a little bug.  After call the `Electronify` function I tried to log the `App .mainWindow` object and it returns `undefined`. :disappointed: 

``` javascript
var Electronify = require('electronify');

var App = new Electronify(__dirname + '/index.html', {
  resizable: true
});

console.log(App.mainWindow); //undefined
```

I imagine that is because the fill of `App` depends of the `ready` event.

In my opinion this can be fixed just emitting a "up" (or other name) event before return the ElectronApp instance. Doing that will be easy knowing that the `app` module from electron extends EventEmmiter.

``` javascript
    //... code
    // Save the browser window
    App.mainWindow = new BrowserWindow(bwOpts);

    App.mainWindow.loadUrl("file://" + path);
    App.mainWindow.on("closed", function() {
        mainWindow = null;
    });

    App.emit('alive', App.mainWindow);

    return App;
}
```

What do you think @IonicaBizau ?

**Comment by IonicaBizau** [comment]
This is already done by Electron, natively, using the `ready` event:

``` js
var Electronify = require('electronify');

var App = new Electronify(__dirname + '/index.html', {
  resizable: true
});

App.on("ready", function () {
    console.log(App.mainWindow); //undefined
});
```

:joy: 

@mapaiva Is this what you want? :smile:

**Comment by mapaiva** [comment]
Duuuuh!! :joy: :joy: :joy: :joy: :joy: :joy: 

This is exactly what I want. I didn't thought about that (obvious) option hahahaha. 

Thank you @IonicaBizau

**Comment by IonicaBizau** [comment]
:grin: :joy:
