### ISSUE TITLE
What is Electronify doing?

### ISSUE THREAD

**Issue by sapioit** [IonicaBizau/electronify#3]
So... what is Eelctronify doing, really?

**Comment by IonicaBizau** [comment]
Hey @sapioit! 

Check out the code! :smile: 
Basically, it's a high-level module for creating common Electron apps, by creating the browser window for you.

For example, look at [this quick-start example](https://github.com/atom/electron-quick-start/blob/master/main.js). It's cool enough, but imagine that in most of the cases you always want to have an HTML file to be loaded and handle the window closing correctly. That obviously means you have to have that piece of code in all your Electron apps which makes it terrible to maintain. Electronify solves that.

So, the quick start example, would look like this, using `electronify`:

``` js
// Dependencies
var Electronify = require("electronify");

// Create the app
var app = Electronify(__dirname + "/app/index.html");
```

If you have any other questions, let me know. :grin:
